SELECT 10 + NULL, 10 - NULL, 10 * NULL, NULL / 10, 10 / NULL FROM DUAL;

SELECT CASE WHEN 0.15 <> NULL THEN 1 ELSE 0 END FROM DUAL;

-- null will NOT be counted
SELECT COUNT(COLUMN_VALUE) FROM TABLE(SYS.ODCINUMBERLIST(1,1,2,3,3,4,4,5,NULL,NULL,NULL));
-- NULL will be counted here
SELECT COUNT(*) FROM TABLE(SYS.ODCINUMBERLIST(1,1,2,3,3,4,4,5,NULL,NULL,NULL));

select sum(case when column_value = '1' then 1 end)
from table(sys.dbms_debug_vc2coll('1', '2', '1', '1', '0', null));

select count(case when column_value = '3' then 1 end)
from table(sys.dbms_debug_vc2coll('1', '2', '1', '1', '0', null, null));

WITH A AS
(
SELECT 1 FROM DUAL UNION ALL
SELECT 2 FROM DUAL UNION ALL
SELECT 5 FROM DUAL UNION ALL
SELECT 20 FROM DUAL UNION ALL
SELECT 29 FROM DUAL UNION ALL
SELECT 40 FROM DUAL
) SELECT * FROM A;

WITH A AS
(
SELECT 1 FROM DUAL UNION ALL
SELECT 2 FROM DUAL UNION ALL
SELECT 5 FROM DUAL UNION ALL
SELECT 20 FROM DUAL UNION ALL
SELECT 29 FROM DUAL UNION ALL
SELECT 40 FROM DUAL
),
B AS
(
SELECT 1 FROM DUAL UNION ALL
SELECT 2 FROM DUAL UNION ALL
SELECT 5 FROM DUAL UNION ALL
SELECT 20 FROM DUAL UNION ALL
SELECT 29 FROM DUAL UNION ALL
SELECT 40 FROM DUAL
)
SELECT A.*, B.* FROM A, B;


DECLARE
  TMP NUMBER;
BEGIN
  SELECT 1
    INTO TMP
    FROM DUAL
   WHERE 1 = 2;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
  DBMS_OUTPUT.PUT_LINE('EXCEPTION');
END;